In [2]:
import numpy as np

np.dot(3,4)


12

In [4]:
a=np.arange(3)
b=np.arange(3,6)
np.dot(a,b)

14

In [7]:
#等同于 矩阵乘法
a=np.arange(6).reshape(3,2)
b=np.arange(2).reshape(2,1)
np.dot(a,b)

array([[1],
       [3],
       [5]])

In [16]:
a=np.arange(12).reshape(2,3,2)
b=np.arange(4).reshape(2,2,1)
np.matmul(a,b)[0]==np.matmul(a[0],b[0])

array([[ True],
       [ True],
       [ True]])

In [17]:
import torch
a=torch.tensor([2,3])
b=torch.tensor([2,1])
torch.dot(a,b)

tensor(7)

In [19]:
a=torch.randn(3)
b=torch.randn(3,4)
torch.matmul(a,b)

tensor([-1.3871, -0.8522, -0.1162,  0.3463])

In [21]:
a=torch.randn(10,3,4)
b=torch.randn(4)
torch.matmul(a,b).size()

torch.Size([10, 3])

In [22]:
a=torch.randn(10,3,4)
b=torch.randn(10,4,5)
torch.matmul(a,b).size()

torch.Size([10, 3, 5])

In [23]:
# 广播逻辑仅适用于批次维度上，在矩阵维度上不适用
a=torch.randn(10,1,3,4)
b=torch.randn(2,4,5)
torch.matmul(a,b).size()

torch.Size([10, 2, 3, 5])